name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "server" ]
  pull_request:
    branches: [ "server" ]

jobs:
  build-and-deploy:
    if: contains(github.event.head_commit.message, 'deploy')
    # commit message가 deploy를 포함할 경우에만 배포
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0'
  
    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x gradlew
    
    - name: Build with Gradle Wrapper
      run: ./gradlew clean build -x test
    
    - name: List contents of build directory
      run: ls -la build/libs
    
    - name: Log in to docker private repo
      uses: docker/login-action@v2
      with:
        registry: "topet.site:5000" # private registry 주소
        # secret 등록 후 하드코딩 대체
        # username: ${{ secrets.DOCKER_USERNAME }}
        # password: ${{ secrets.DOCKER_PASSWORD }}
        username: admin
        password: docker12345
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . 
        file: ./docker/Dockerfile
        push: true
        tags: "topet.site:5000/topet:${{ github.run_id }}"


    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        # secret 등록 후 하드코딩 대체
        # host: ${{ secrets.HOST }} 
        # username: ${{ secrets.USERNAME }}
        # key: ${{ secrets.SSH_KEY }}
        host: 175.45.202.131
        username: root
        key: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
          NhAAAAAwEAAQAAAgEAupBoig6psNqgbWbbmCYtmBmsURb6ug5jTVztDWi45Yhgr10DFuAJ
          I628d0tXZUDJanve4u6dhwy3bY42m1ePmrUQhaFeeP6Dle+TMdm+k2LcZN+xBsaT2S80H2
          8IJpIs1ntb9KLQo5rl3IIoWbY0rLXaKqrzoly2niwH9WtTeMwZgBpYQ4oW6MfDr/dWiqG3
          QmniuHIcGow477IAyZAxtLCnwP0Rj4WMvBw8NJ7XI4rFkyaDePM4Z5e74AgdEPMVcpc+Ay
          qk+/1M4YA+pkM/izaXLfOmbxY4gFRAjwL8FwWaz8Iv8UY2JxdahrjgvpX3mrtr1scj3Icw
          Hfp9Ku7NMhPhQZSt3CRoClyIm0sbAMzOtaVYc6p4hjsG9nIbGzIy3h3FsUwSeojkDD/8Tc
          RDmrO4IqO7SmKYooW12uYWHQ7zhXwc71pcfKelUNXML3wISTj2C9xzYftxge4c9crSbrBR
          Yqk8bOz/LbX2+QYLGiLCV6KubsvwDNMeouIlY3kz1vjqX6UZsNFM3Vl+nySGwiYUrq/f7Q
          mwhA53LiuoMy87jfZKhpYn39VosHK/WPZS9vWBf8MZ2r4PpB+HTywe5YmICwthln5HOHoV
          V7yjQ0RX9gny9RiaW/+R3eVaCVQydpq+SoNJDGg0K/r8j3dd5ZJkjTqV+AxVNBA6VEDayG
          0AAAdQ8WmiM/FpojMAAAAHc3NoLXJzYQAAAgEAupBoig6psNqgbWbbmCYtmBmsURb6ug5j
          TVztDWi45Yhgr10DFuAJI628d0tXZUDJanve4u6dhwy3bY42m1ePmrUQhaFeeP6Dle+TMd
          m+k2LcZN+xBsaT2S80H28IJpIs1ntb9KLQo5rl3IIoWbY0rLXaKqrzoly2niwH9WtTeMwZ
          gBpYQ4oW6MfDr/dWiqG3QmniuHIcGow477IAyZAxtLCnwP0Rj4WMvBw8NJ7XI4rFkyaDeP
          M4Z5e74AgdEPMVcpc+Ayqk+/1M4YA+pkM/izaXLfOmbxY4gFRAjwL8FwWaz8Iv8UY2Jxda
          hrjgvpX3mrtr1scj3IcwHfp9Ku7NMhPhQZSt3CRoClyIm0sbAMzOtaVYc6p4hjsG9nIbGz
          Iy3h3FsUwSeojkDD/8TcRDmrO4IqO7SmKYooW12uYWHQ7zhXwc71pcfKelUNXML3wISTj2
          C9xzYftxge4c9crSbrBRYqk8bOz/LbX2+QYLGiLCV6KubsvwDNMeouIlY3kz1vjqX6UZsN
          FM3Vl+nySGwiYUrq/f7QmwhA53LiuoMy87jfZKhpYn39VosHK/WPZS9vWBf8MZ2r4PpB+H
          Tywe5YmICwthln5HOHoVV7yjQ0RX9gny9RiaW/+R3eVaCVQydpq+SoNJDGg0K/r8j3dd5Z
          JkjTqV+AxVNBA6VEDayG0AAAADAQABAAACACnCeDvq003safuDCgVRCmSg3oLaJ24tGUow
          UjltpvFt6OJn6fCdXj5XvbdgLGRUL6F/r6DRM36OuKIzsoJsA49oFxYqTDi+E5skoKiIal
          GYT+fecEQpf9+d4sdkdYkYsCOkQi2MojH00p3cnoaSM9Ey9W4WjOlbYl8eUPu8tdb0rIKR
          ow8fIkihqmpBbWQjlZ8uj1qk5CiHGZmBmQ6FEbM11Z7rppofFSToFwvaQCLLBbWN6eDRZF
          8/xgR8HHF2T+cx9mYEDiD/jk1thNh3dgpFwmo9PxRff28uLLM2QlIu5Xu6pjuV8TonzpIY
          YOoYLG+8owNU2PCcbAdR0eGhyVkYzY1x3gDYXuu5YqxvoCKo9pKSjqhdIzKr+b/0Wc1LfK
          9rHzZ3ZyESTSd0jZVHp7a01IK6NVoK/O7gsmuk4rOU1MSNrok29KCVVoIOeY1Ub6l87RLb
          lYGMpWCtG4zS5g05OdUGRfXou+xUAVs6Rq8bAs7dvKKOR6RDjuiU2OyWjHFI6kXy03HFYa
          yJLFmJJASmwewcknl+Vl313BELtueallmdCtGR60jc5T3jKl7/Jr/rRz+viyKi/6uPlEhk
          MAe8AijV045siemoN/mM8a4Kl8Nq0AXo18C2dF3hAsy+Krhv59bCobskusBj42HTmvfkTu
          bocZdRoYRjTBleXyiLAAABAQCJQiypLcMc8kgwqVNDKUNZRuEthZAzRz6jC7T3zJVNFFNB
          CW8CfEZr65uRrHxCB1x7+DoL8wy3/Kn3TJNkmKH5v/ukogUjxdT6KqB/Fye6qq5qp/yzhD
          3lgflYnrr/9TyWjOhPrMVX6wVE1WyiiaWwu6Kar9o9roePW/Q299VRvmuKEyX0u+Hyn56z
          H/QSzf5Xaq+E+jfRdJVi8U0kxKHuL6BZ9VMaa3gOuhRdC6i55LZ6hVCeBTSj3EOJ8+X6Ue
          PaLaHp4R9mva3x9KXPBUD+ij5BTDdbGpI5KSbiiyqHriGMHJUOVk5HeR+qkpTly22Q7KOh
          LeYzKibZvR3hDASwAAABAQD92mfHbO2jA8soPNLNheCQ48uxTSE2lAwPWfgRlThL8sn2yc
          yqljwtYb5l/5ckWn9BciropLzJGSRgdi/zQnn7s1iWZIK2f8OcTFvI1HKoTUJKXxaBmE2h
          0YItjZyQQeyg+6SKeMnYjii/Zc7Mogrw7crEv4qTkKd8gdFwrKC2z55xSRfQRjQBfdOErA
          6ElKzFyOJTKnspzTssnGUycpMwnnkVj69v78vP4bsPqC7IHD9T7R6+6uFvYiCZFBaNmAHz
          ve+z2j9iDAkNfxINjUswBK5+aky3XLTvzUxQcoIMJ3OpcTyRD+MocLQoaERmwZ4Z3b5Ijk
          rRBYegrZ+JnoYrAAABAQC8JFJNtDOhuVZQIedJYoM06CxleQw3HiFpMUiT4tQoJ68CNkh+
          PbLzMM+1957cWBcimtuhbvlNZNRnhecdZstr92N30fCWq/+b13QzQPLdZg8CphMtHCKYqO
          /oIqEBn5wixkolhKBapEozsf7JNaizVAZGIlUax93Vz6jh23CHpnoj1Z55hgCtBVJccAXy
          /q2bTlKALUE03mbitZJze2OjzGoTjIFvByPj6hXCt+nWcFKJOTtr4al5f2Onrgp2Hr3j0M
          agHCjWOolAdZuNyPLUn4p6SwikksdIFNaYLp6+vx1RXWl8oPJ6sHPyK3yHy/2hS8+YBFAQ
          kUNz5Sv4B/fHAAAAFnlvdXJfZW1haWxAZXhhbXBsZS5jb20BAgME
          -----END OPENSSH PRIVATE KEY-----        
        port: 22
        script: |
            docker pull topet.site:5000/topet:${{ github.run_id }}
            sed -i "s|topet.site:5000/topet:[^ ]*|topet.site:5000/topet:${{ github.run_id }}|" /root/dockercompose/docker-compose.yml 
            cd /root/dockercompose && docker-compose up -d --force-recreatels
            

