name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "server" ]
  pull_request:
    branches: [ "server" ]

jobs:
  build-and-deploy:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0'
  
    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x gradlew
    
    - name: Build with Gradle Wrapper
      run: ./gradlew clean build -x test
    
    - name: List contents of build directory
      run: ls -la build/libs
    
    - name: Log in to docker private repo
      uses: docker/login-action@v2
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_BUILDKIT_INLINE_CACHE: 1
        DOCKER_DAEMON_ALLOW_INSECURE_REGISTRY: true
      with:
        registry: "topet.site:5000"
        username: admin
        password: docker12345
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile
        push: true
        tags: "topet.site:5000/topet:latest"
